openapi: 3.0.3
info:
  description: Basic API template
  version: 1.0.0
  title: Basic API
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'http://localhost:8080'
    description: localhost
tags:
  - name: system
    description: System health operations
  - name: users
    description: Users use cases
paths:
  /health:
    get:
      tags:
        - system
      operationId: getHealth
      summary: Health check
      description: Checks the API itself and all critical dependencies (available under the port 8079 or HTTP_HEALTH_PORT  environment variable). For internal purposes
      x-internal: true
      responses:
        '200':
          description: OK
  /users:
    get:
      tags:
        - users
      operationId: getAllUsers
      summary: Get all users
      description: Retrieve all users from datasource
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  '/users/{userId}':
    get:
      summary: Get user by id
      tags:
        - users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: getUserById
      description: Retrieve user information from ID
    parameters:
      - schema:
          type: integer
          exclusiveMinimum: true
          minimum: 0
        name: userId
        in: path
        required: true
        description: Numeric ID of the user to get
components:
  schemas:
    User:
      title: User
      x-stoplight:
        id: e04lplqp2mw1t
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        firstname:
          type: string
      description: ''
